import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/huggzer-dev/deepseek-ai
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:fs",
    "node:path",
    "node:os",
    "node:child_process",
    "node:crypto",
    "node:stream",
    "node:util",
    "node:events",
    "node:buffer",
    "node:url",
    "node:querystring",
    "node:http",
    "node:https",
    "node:zlib",
    "node:tty",
    "node:dgram",
    "node:dns",
    "node:net",
    "node:readline",
    "node:vm",
    "node:worker_threads",
    "node:assert",
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}